### ISSUE TITLE
Cricbuzz scraping problem.

### ISSUE THREAD

**Issue by l3satwik** [l3satwik/cric-score#1]
Cricbuzz has two different html structure and switches between them. An alternate method has to be added.

**Comment by parthiv-p** [comment]
Consider scraping the XML on http://synd.cricbuzz.com/j2me/1.0/livematches.xml.

**Comment by l3satwik** [comment]
Thanks! I also want to trigger an event when 6 has been hit or a wicket falls. I don't think this XML has any fields for ball-by-ball updates.

**Comment by parthiv-p** [comment]
It's not directly available but you can develop the logic. Open the commentary and scorecard link for each match by finding the match 'datapath' (from the above XML) and the datapath + 'commentary.xml' or datapath + 'scorecard.xml'

**Comment by l3satwik** [comment]
This is going to make everything so easy. Thanks!
But how did you come to know about these XMLs? I couldn't find anything for developers on the Cricbuzz website!
